### ISSUE TITLE
'HomeAssistant' object has no attribute 'helpers'

### ISSUE THREAD

**Issue by walk0080** [vaparr/ha-overseerr#31]
Started happening at some point after HA 2025.4.x?

HA Core:
`2025.5.1`

HA error log entry:
```
Logger: homeassistant.setup
Source: setup.py:426
First occurred: 9:58:15 AM (1 occurrence)
Last logged: 9:58:15 AM

Error during setup of component overseerr: 'HomeAssistant' object has no attribute 'helpers'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 426, in _async_setup_component
    result = await task
             ^^^^^^^^^^
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/overseerr/__init__.py", line 198, in setup
    hass.helpers.discovery.load_platform("sensor", DOMAIN, {}, config)
    ^^^^^^^^^^^^
AttributeError: 'HomeAssistant' object has no attribute 'helpers'
```

HA configuration.yaml entry:
`overseerr:
  host: 192.168.1.2
  port: 5055
  api_key: REDACTED
  scan_interval: 600`

**Comment by walk0080** [comment]
Gave up and deleted from my system.

**Comment by Alcedema** [comment]
I can confirm that replacing __init__.py with @RobertD502 version ( https://github.com/vaparr/ha-overseerr/blob/18e318716afa70d14bd77b983ef6f58205062390/custom_components/overseerr/__init__.py ) works on HAOS 2025.5.2

**Comment by RobertD502** [comment]
Home Assistant has an official Overseer integration now (since 1 or 2 major releases ago, I believe). Use that instead.

**Comment by Alcedema** [comment]
I would, but that integration doesn't integrate the Overseerr Issues subsystem, as far as I found.
